kind: pipeline
type: docker
name: default

steps:
  - name: build
    image:  banzaicloud/drone-kaniko
    settings:
      dockerfile: Dockerfile
      repo: xnv/aurum
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
      registry: k2so.xnv.io
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: unit_test
    image: k2so.xnv.io/xnv/aurum:${DRONE_COMMIT_SHA:0:8}
    commands:
      - "python3 -m unittest tests"

  - name: deploy_internal_pypi
    image: k2so.xnv.io/xnv/aurum:${DRONE_COMMIT_SHA:0:8}
    settings:
      pypirc:
        from_secret: pypirc
    environment:
        PYPIRC:
          from_secret: pypirc
    commands:
      - "echo $PYPIRC | base64 -d > /root/.pypirc"
      - "cat /root/.pypirc"
      - "python3 setup.py -vvv sdist upload -r internal"

  - name: slack
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook
      channel: amalgam
      template: >
        {{#success build.status}}
          Aurum: #build {{build.number}} succeeded. Good job.
        Commit: `${DRONE_COMMIT_SHA:0:8}`
        ${DRONE_BUILD_LINK}
        {{else}}
         Aurum: build #{{build.number}} failed. Fix me please.
        Commit: `${DRONE_COMMIT_SHA:0:8}`
        ${DRONE_BUILD_LINK}
        {{/success}}


trigger:
  branch:
    - master
    - develop

image_pull_secrets:
  - dockerconfigjson
