REPOSITORY_DIR = ".au"
KEEP_FILE = ".keep"

DATASET_METADATA_DIR = "datasets"
PARAMETER_METADATA_DIR = "parameters"
METRICS_METADATA_DIR = "metrics"
REQUIREMENTS_METADATA_DIR = "requirements"
EXPERIMENTS_METADATA_DIR = "experiments"
